language: python

services:
  - docker

before_install:
  - pip install poetry
  - poetry config virtualenvs.create false

install:
  - cp ./app/pyproject.toml ./
  - poetry install --no-root --no-dev
script:
  - pytest
after_success:
  - docker build . -t blzface/future-of-security
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push  blzface/future-of-security