sudo: required

language: python

services:
  - docker

after_success:
  - docker build . -t blzface/future-of-security:backend-$TRAVIS_BUILD_NUMBER
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push  blzface/future-of-security:backend-$TRAVIS_BUILD_NUMBER