language: python

services:
  - docker

before_install:
  - poetry config virtualenvs.create false

install:
  - cd /app/
  - poetry install --no-root --no-dev

after_success:
  - docker build . -t blzface/future-of-security:backend-$TRAVIS_BUILD_NUMBER
  - echo "$DockerPassword" | docker login --username "$DockerUsername" --password-stdin; docker push  blzface/future-of-security:backend-$TRAVIS_BUILD_NUMBER