apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: blzface/future-of-security
        ports:
        - containerPort: 4000
        volumeMounts:
          - name: mongo
            mountPath: /etc/secrets
            readOnly: true
        env:
          - name: RUN_ENV
            value: PROD
        command: ["echo /etc/secrets/password > $MONGO_PASSWORD"]
      volumes:
        - name: mongo
          secret:
            secretName: secret-mongo
