[tool.poetry]
name = "future-security"
version = "0.1.0"
description = ""
authors = ["Nate <nateb@vt.edu>"]

[tool.poetry.dependencies]
dnspython = "*"
pytest = "*"
pymongo = "3.12.0 "
certifi = "2021.5.30"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
